apiVersion: v1
kind: Secret
metadata:
  name: cluster-kube-prod-fsn
  namespace: blackbox-probe-controller-system
  labels:
    blackbox-probe-controller.tapclap.com/cluster-config: "true"
  annotations:
    blackbox-probe-controller.tapclap.com/cluster-name: kube-prod-fsn
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: https://kubernetes.default.svc
      name: remote
    contexts:
    - context:
        cluster: remote
        user: remote
      name: remote
    current-context: remote
    users:
    - name: remote
      user:
        token: replace-me
