---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vmprobe-manager-role
  namespace: monitoring
rules:
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmprobes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
